//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendor.Services.Drivecam.Submission
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://DriveCam.com/Classes")]
    public partial class LoginResponse : object
    {
        
        private long CompanyIdField;
        
        private bool ErrorField;
        
        private string MessageField;
        
        private string SessionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitDriverDispatchLogsResponse", Namespace="http://DriveCam.com/Classes")]
    public partial class SubmitDriverDispatchLogsResponse : object
    {
        
        private bool ErrorField;
        
        private string MessageField;
        
        private long SubmissionIdField;
        
        private string ValidationResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SubmissionId
        {
            get
            {
                return this.SubmissionIdField;
            }
            set
            {
                this.SubmissionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidationResponse
        {
            get
            {
                return this.ValidationResponseField;
            }
            set
            {
                this.ValidationResponseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSubmissionStatusResponse", Namespace="http://DriveCam.com/Classes")]
    public partial class GetSubmissionStatusResponse : object
    {
        
        private bool ErrorField;
        
        private string MessageField;
        
        private long SubmissionStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SubmissionStatus
        {
            get
            {
                return this.SubmissionStatusField;
            }
            set
            {
                this.SubmissionStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSubmissionResultsResponse", Namespace="http://DriveCam.com/Classes")]
    public partial class GetSubmissionResultsResponse : object
    {
        
        private bool ErrorField;
        
        private string MessageField;
        
        private string SubmissionResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionResults
        {
            get
            {
                return this.SubmissionResultsField;
            }
            set
            {
                this.SubmissionResultsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVehiclesRequest", Namespace="http://DriveCam.com/Classes")]
    public partial class GetVehiclesRequest : object
    {
        
        private System.Nullable<long> GroupIdField;
        
        private bool IncludeSubgroupsField;
        
        private string SessionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> GroupId
        {
            get
            {
                return this.GroupIdField;
            }
            set
            {
                this.GroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeSubgroups
        {
            get
            {
                return this.IncludeSubgroupsField;
            }
            set
            {
                this.IncludeSubgroupsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVehiclesResponse", Namespace="http://DriveCam.com/Classes")]
    public partial class GetVehiclesResponse : object
    {
        
        private bool ErrorField;
        
        private string MessageField;
        
        private Vendor.Services.Drivecam.Submission.VehicleInfo[] VehiclesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vendor.Services.Drivecam.Submission.VehicleInfo[] Vehicles
        {
            get
            {
                return this.VehiclesField;
            }
            set
            {
                this.VehiclesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleInfo", Namespace="http://DriveCam.com/Classes")]
    public partial struct VehicleInfo
    {
        
        private System.Nullable<long> AssignedDriverField;
        
        private System.DateTime CreationDateField;
        
        private System.Nullable<System.DateTime> InServiceDateField;
        
        private System.DateTime LastConnectedField;
        
        private string LicenseNumberField;
        
        private string NameField;
        
        private int ObjectRevisionField;
        
        private System.Nullable<System.DateTime> RevisionDateField;
        
        private long VehicleIdField;
        
        private int VehicleStatusIdField;
        
        private long VehicleTypeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AssignedDriver
        {
            get
            {
                return this.AssignedDriverField;
            }
            set
            {
                this.AssignedDriverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InServiceDate
        {
            get
            {
                return this.InServiceDateField;
            }
            set
            {
                this.InServiceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastConnected
        {
            get
            {
                return this.LastConnectedField;
            }
            set
            {
                this.LastConnectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenseNumber
        {
            get
            {
                return this.LicenseNumberField;
            }
            set
            {
                this.LicenseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ObjectRevision
        {
            get
            {
                return this.ObjectRevisionField;
            }
            set
            {
                this.ObjectRevisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RevisionDate
        {
            get
            {
                return this.RevisionDateField;
            }
            set
            {
                this.RevisionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long VehicleId
        {
            get
            {
                return this.VehicleIdField;
            }
            set
            {
                this.VehicleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehicleStatusId
        {
            get
            {
                return this.VehicleStatusIdField;
            }
            set
            {
                this.VehicleStatusIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long VehicleTypeId
        {
            get
            {
                return this.VehicleTypeIdField;
            }
            set
            {
                this.VehicleTypeIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExistingSessionRequest", Namespace="http://DriveCam.com/Classes")]
    public partial class ExistingSessionRequest : object
    {
        
        private string SessionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVehicleTypesResponse", Namespace="http://DriveCam.com/Classes")]
    public partial class GetVehicleTypesResponse : object
    {
        
        private bool ErrorField;
        
        private string MessageField;
        
        private Vendor.Services.Drivecam.Submission.VehicleType[] VehicleTypesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vendor.Services.Drivecam.Submission.VehicleType[] VehicleTypes
        {
            get
            {
                return this.VehicleTypesField;
            }
            set
            {
                this.VehicleTypesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleType", Namespace="http://DriveCam.com/Classes")]
    public partial struct VehicleType
    {
        
        private System.DateTime CreationDateField;
        
        private string DescriptionField;
        
        private long VehicleTypeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long VehicleTypeId
        {
            get
            {
                return this.VehicleTypeIdField;
            }
            set
            {
                this.VehicleTypeIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVehicleStatusesResponse", Namespace="http://DriveCam.com/Classes")]
    public partial class GetVehicleStatusesResponse : object
    {
        
        private bool ErrorField;
        
        private string MessageField;
        
        private Vendor.Services.Drivecam.Submission.VehicleStatus[] VehicleStatusesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vendor.Services.Drivecam.Submission.VehicleStatus[] VehicleStatuses
        {
            get
            {
                return this.VehicleStatusesField;
            }
            set
            {
                this.VehicleStatusesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleStatus", Namespace="http://DriveCam.com/Classes")]
    public partial struct VehicleStatus
    {
        
        private System.DateTime CreationDateField;
        
        private string DescriptionField;
        
        private int VehicleStatusIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehicleStatusId
        {
            get
            {
                return this.VehicleStatusIdField;
            }
            set
            {
                this.VehicleStatusIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEventTypesResponse", Namespace="http://DriveCam.com/Classes")]
    public partial class GetEventTypesResponse : object
    {
        
        private bool ErrorField;
        
        private Vendor.Services.Drivecam.Submission.EventType[] EventTypesField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vendor.Services.Drivecam.Submission.EventType[] EventTypes
        {
            get
            {
                return this.EventTypesField;
            }
            set
            {
                this.EventTypesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventType", Namespace="http://DriveCam.com/Classes")]
    public partial struct EventType
    {
        
        private System.DateTime CreationDateField;
        
        private string DescriptionField;
        
        private long EventTypeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EventTypeId
        {
            get
            {
                return this.EventTypeIdField;
            }
            set
            {
                this.EventTypeIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEventStatusesResponse", Namespace="http://DriveCam.com/Classes")]
    public partial class GetEventStatusesResponse : object
    {
        
        private bool ErrorField;
        
        private Vendor.Services.Drivecam.Submission.EventStatus[] EventStatusesField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vendor.Services.Drivecam.Submission.EventStatus[] EventStatuses
        {
            get
            {
                return this.EventStatusesField;
            }
            set
            {
                this.EventStatusesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventStatus", Namespace="http://DriveCam.com/Classes")]
    public partial struct EventStatus
    {
        
        private System.DateTime CreationDateField;
        
        private string DescriptionField;
        
        private long EventStatusIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EventStatusId
        {
            get
            {
                return this.EventStatusIdField;
            }
            set
            {
                this.EventStatusIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBehaviorsResponse", Namespace="http://DriveCam.com/Classes")]
    public partial class GetBehaviorsResponse : object
    {
        
        private Vendor.Services.Drivecam.Submission.Behavior[] BehaviorsField;
        
        private bool ErrorField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vendor.Services.Drivecam.Submission.Behavior[] Behaviors
        {
            get
            {
                return this.BehaviorsField;
            }
            set
            {
                this.BehaviorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Behavior", Namespace="http://DriveCam.com/Classes")]
    public partial struct Behavior
    {
        
        private long BehaviorIdField;
        
        private System.DateTime CreationDateField;
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BehaviorId
        {
            get
            {
                return this.BehaviorIdField;
            }
            set
            {
                this.BehaviorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUsersRequest", Namespace="http://DriveCam.com/Classes")]
    public partial class GetUsersRequest : object
    {
        
        private System.Nullable<long> GroupIdField;
        
        private bool IncludeSubgroupsField;
        
        private string SessionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> GroupId
        {
            get
            {
                return this.GroupIdField;
            }
            set
            {
                this.GroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeSubgroups
        {
            get
            {
                return this.IncludeSubgroupsField;
            }
            set
            {
                this.IncludeSubgroupsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUsersResponse", Namespace="http://DriveCam.com/Classes")]
    public partial class GetUsersResponse : object
    {
        
        private bool ErrorField;
        
        private string MessageField;
        
        private Vendor.Services.Drivecam.Submission.UserInfo[] UsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vendor.Services.Drivecam.Submission.UserInfo[] Users
        {
            get
            {
                return this.UsersField;
            }
            set
            {
                this.UsersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://DriveCam.com/Classes")]
    public partial struct UserInfo
    {
        
        private System.DateTime CreationDateField;
        
        private System.Nullable<System.DateTime> DobField;
        
        private string EmailField;
        
        private string EmployeeNumberField;
        
        private System.Nullable<System.DateTime> EmploymentEndField;
        
        private System.Nullable<System.DateTime> EmploymentStartField;
        
        private string FirstNameField;
        
        private string GenderField;
        
        private string LastNameField;
        
        private int ObjectRevisionField;
        
        private System.Nullable<System.DateTime> RevisionDateField;
        
        private long UserIdField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Dob
        {
            get
            {
                return this.DobField;
            }
            set
            {
                this.DobField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeNumber
        {
            get
            {
                return this.EmployeeNumberField;
            }
            set
            {
                this.EmployeeNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EmploymentEnd
        {
            get
            {
                return this.EmploymentEndField;
            }
            set
            {
                this.EmploymentEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EmploymentStart
        {
            get
            {
                return this.EmploymentStartField;
            }
            set
            {
                this.EmploymentStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ObjectRevision
        {
            get
            {
                return this.ObjectRevisionField;
            }
            set
            {
                this.ObjectRevisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RevisionDate
        {
            get
            {
                return this.RevisionDateField;
            }
            set
            {
                this.RevisionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetGroupsByIdRequest", Namespace="http://DriveCam.com/Classes")]
    public partial class GetGroupsByIdRequest : object
    {
        
        private System.Nullable<long> GroupIdField;
        
        private bool IncludeSubgroupsField;
        
        private string SessionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> GroupId
        {
            get
            {
                return this.GroupIdField;
            }
            set
            {
                this.GroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeSubgroups
        {
            get
            {
                return this.IncludeSubgroupsField;
            }
            set
            {
                this.IncludeSubgroupsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetGroupsResponse", Namespace="http://DriveCam.com/Classes")]
    public partial class GetGroupsResponse : object
    {
        
        private bool ErrorField;
        
        private Vendor.Services.Drivecam.Submission.GroupInfo[] GroupsField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vendor.Services.Drivecam.Submission.GroupInfo[] Groups
        {
            get
            {
                return this.GroupsField;
            }
            set
            {
                this.GroupsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupInfo", Namespace="http://DriveCam.com/Classes")]
    public partial struct GroupInfo
    {
        
        private System.DateTime CreationDateField;
        
        private string FullPathField;
        
        private long GroupIdField;
        
        private string NameField;
        
        private int ObjectRevisionField;
        
        private System.Nullable<System.DateTime> RevisionDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullPath
        {
            get
            {
                return this.FullPathField;
            }
            set
            {
                this.FullPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long GroupId
        {
            get
            {
                return this.GroupIdField;
            }
            set
            {
                this.GroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ObjectRevision
        {
            get
            {
                return this.ObjectRevisionField;
            }
            set
            {
                this.ObjectRevisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RevisionDate
        {
            get
            {
                return this.RevisionDateField;
            }
            set
            {
                this.RevisionDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetGroupsByFullPathRequest", Namespace="http://DriveCam.com/Classes")]
    public partial class GetGroupsByFullPathRequest : object
    {
        
        private bool IncludeSubgroupsField;
        
        private string PathField;
        
        private string SessionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeSubgroups
        {
            get
            {
                return this.IncludeSubgroupsField;
            }
            set
            {
                this.IncludeSubgroupsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEventsByLastUpdateDateRequest", Namespace="http://DriveCam.com/Classes")]
    public partial class GetEventsByLastUpdateDateRequest : object
    {
        
        private System.DateTime EndDateField;
        
        private System.Nullable<long> GroupIdField;
        
        private bool IncludeSubgroupsField;
        
        private string SessionIdField;
        
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> GroupId
        {
            get
            {
                return this.GroupIdField;
            }
            set
            {
                this.GroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeSubgroups
        {
            get
            {
                return this.IncludeSubgroupsField;
            }
            set
            {
                this.IncludeSubgroupsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEventsResponse", Namespace="http://schemas.datacontract.org/2004/07/DriveCam.HindSight.Messaging.Messages.Mes" +
        "sageClasses.Api.GetEvents_V5")]
    public partial class GetEventsResponse : object
    {
        
        private bool ErrorField;
        
        private Vendor.Services.Drivecam.Submission.EventsInfoV5[] EventsField;
        
        private string MessageField;
        
        private System.Nullable<System.DateTime> QueryCutoffField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vendor.Services.Drivecam.Submission.EventsInfoV5[] Events
        {
            get
            {
                return this.EventsField;
            }
            set
            {
                this.EventsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> QueryCutoff
        {
            get
            {
                return this.QueryCutoffField;
            }
            set
            {
                this.QueryCutoffField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventsInfoV5", Namespace="http://DriveCam.com/Classes/")]
    public partial class EventsInfoV5 : Vendor.Services.Drivecam.Submission.EventsInfoV4
    {
        
        private string EventLink2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventLink2
        {
            get
            {
                return this.EventLink2Field;
            }
            set
            {
                this.EventLink2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventsInfo", Namespace="http://DriveCam.com/Classes/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vendor.Services.Drivecam.Submission.EventsInfoV3))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vendor.Services.Drivecam.Submission.EventsInfoV4))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vendor.Services.Drivecam.Submission.EventsInfoV5))]
    public partial class EventsInfo : object
    {
        
        private Vendor.Services.Drivecam.Submission.EventBehavior[] BehaviorsField;
        
        private System.Nullable<long> CoachIdField;
        
        private System.DateTime CreationDateField;
        
        private long CustomerEventIdField;
        
        private string CustomerEventIdStringField;
        
        private System.Nullable<System.DateTime> DownloadedDateField;
        
        private System.Nullable<long> DriverIdField;
        
        private string ERSerialNumberField;
        
        private long EventIdField;
        
        private long EventStatusIdField;
        
        private long EventTypeIdField;
        
        private System.Nullable<decimal> ForwardMaxField;
        
        private System.Nullable<decimal> ForwardThresholdField;
        
        private long GroupIdField;
        
        private System.Nullable<decimal> HeadingField;
        
        private System.DateTime LastUpdatedField;
        
        private System.Nullable<decimal> LateralMaxField;
        
        private System.Nullable<decimal> LateralThresholdField;
        
        private System.Nullable<decimal> LatitudeField;
        
        private System.Nullable<decimal> LongitudeField;
        
        private string NotesField;
        
        private int ObjectRevisionField;
        
        private System.Nullable<decimal> OverdueField;
        
        private string RecordDateTZField;
        
        private System.DateTime RecordDateUTCField;
        
        private int RecordDateUtcOffsetField;
        
        private System.Nullable<System.DateTime> ReviewedDateField;
        
        private System.Nullable<System.DateTime> RevisionDateField;
        
        private long ScoreField;
        
        private System.Nullable<decimal> ShockThresholdField;
        
        private System.Nullable<decimal> SpeedField;
        
        private System.Nullable<long> VehicleIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vendor.Services.Drivecam.Submission.EventBehavior[] Behaviors
        {
            get
            {
                return this.BehaviorsField;
            }
            set
            {
                this.BehaviorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CoachId
        {
            get
            {
                return this.CoachIdField;
            }
            set
            {
                this.CoachIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CustomerEventId
        {
            get
            {
                return this.CustomerEventIdField;
            }
            set
            {
                this.CustomerEventIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerEventIdString
        {
            get
            {
                return this.CustomerEventIdStringField;
            }
            set
            {
                this.CustomerEventIdStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DownloadedDate
        {
            get
            {
                return this.DownloadedDateField;
            }
            set
            {
                this.DownloadedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DriverId
        {
            get
            {
                return this.DriverIdField;
            }
            set
            {
                this.DriverIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERSerialNumber
        {
            get
            {
                return this.ERSerialNumberField;
            }
            set
            {
                this.ERSerialNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EventId
        {
            get
            {
                return this.EventIdField;
            }
            set
            {
                this.EventIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EventStatusId
        {
            get
            {
                return this.EventStatusIdField;
            }
            set
            {
                this.EventStatusIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EventTypeId
        {
            get
            {
                return this.EventTypeIdField;
            }
            set
            {
                this.EventTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ForwardMax
        {
            get
            {
                return this.ForwardMaxField;
            }
            set
            {
                this.ForwardMaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ForwardThreshold
        {
            get
            {
                return this.ForwardThresholdField;
            }
            set
            {
                this.ForwardThresholdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long GroupId
        {
            get
            {
                return this.GroupIdField;
            }
            set
            {
                this.GroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Heading
        {
            get
            {
                return this.HeadingField;
            }
            set
            {
                this.HeadingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdated
        {
            get
            {
                return this.LastUpdatedField;
            }
            set
            {
                this.LastUpdatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LateralMax
        {
            get
            {
                return this.LateralMaxField;
            }
            set
            {
                this.LateralMaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LateralThreshold
        {
            get
            {
                return this.LateralThresholdField;
            }
            set
            {
                this.LateralThresholdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ObjectRevision
        {
            get
            {
                return this.ObjectRevisionField;
            }
            set
            {
                this.ObjectRevisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Overdue
        {
            get
            {
                return this.OverdueField;
            }
            set
            {
                this.OverdueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecordDateTZ
        {
            get
            {
                return this.RecordDateTZField;
            }
            set
            {
                this.RecordDateTZField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RecordDateUTC
        {
            get
            {
                return this.RecordDateUTCField;
            }
            set
            {
                this.RecordDateUTCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordDateUtcOffset
        {
            get
            {
                return this.RecordDateUtcOffsetField;
            }
            set
            {
                this.RecordDateUtcOffsetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReviewedDate
        {
            get
            {
                return this.ReviewedDateField;
            }
            set
            {
                this.ReviewedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RevisionDate
        {
            get
            {
                return this.RevisionDateField;
            }
            set
            {
                this.RevisionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                this.ScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ShockThreshold
        {
            get
            {
                return this.ShockThresholdField;
            }
            set
            {
                this.ShockThresholdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Speed
        {
            get
            {
                return this.SpeedField;
            }
            set
            {
                this.SpeedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> VehicleId
        {
            get
            {
                return this.VehicleIdField;
            }
            set
            {
                this.VehicleIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventsInfoV3", Namespace="http://DriveCam.com/Classes/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vendor.Services.Drivecam.Submission.EventsInfoV4))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vendor.Services.Drivecam.Submission.EventsInfoV5))]
    public partial class EventsInfoV3 : Vendor.Services.Drivecam.Submission.EventsInfo
    {
        
        private string EventLinkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventLink
        {
            get
            {
                return this.EventLinkField;
            }
            set
            {
                this.EventLinkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventsInfoV4", Namespace="http://DriveCam.com/Classes/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vendor.Services.Drivecam.Submission.EventsInfoV5))]
    public partial class EventsInfoV4 : Vendor.Services.Drivecam.Submission.EventsInfoV3
    {
        
        private Vendor.Services.Drivecam.Submission.NoteInfo[] EventNotesField;
        
        private bool IsCoachableField;
        
        private Vendor.Services.Drivecam.Submission.NoteInfo[] ReviewNotesField;
        
        private Vendor.Services.Drivecam.Submission.NoteInfo[] SessionNotesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vendor.Services.Drivecam.Submission.NoteInfo[] EventNotes
        {
            get
            {
                return this.EventNotesField;
            }
            set
            {
                this.EventNotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCoachable
        {
            get
            {
                return this.IsCoachableField;
            }
            set
            {
                this.IsCoachableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vendor.Services.Drivecam.Submission.NoteInfo[] ReviewNotes
        {
            get
            {
                return this.ReviewNotesField;
            }
            set
            {
                this.ReviewNotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vendor.Services.Drivecam.Submission.NoteInfo[] SessionNotes
        {
            get
            {
                return this.SessionNotesField;
            }
            set
            {
                this.SessionNotesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventBehavior", Namespace="http://schemas.datacontract.org/2004/07/DriveCam.HindSight.Messaging.Messages.Mes" +
        "sageClasses.Api")]
    public partial class EventBehavior : object
    {
        
        private System.Nullable<long> BehaviorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Behavior
        {
            get
            {
                return this.BehaviorField;
            }
            set
            {
                this.BehaviorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoteInfo", Namespace="http://DriveCam.com/Classes")]
    public partial class NoteInfo : object
    {
        
        private string AuthorFirstNameField;
        
        private string AuthorLastNameField;
        
        private string AuthorUserNameField;
        
        private string ContentField;
        
        private System.Nullable<System.DateTime> TimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorFirstName
        {
            get
            {
                return this.AuthorFirstNameField;
            }
            set
            {
                this.AuthorFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorLastName
        {
            get
            {
                return this.AuthorLastNameField;
            }
            set
            {
                this.AuthorLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorUserName
        {
            get
            {
                return this.AuthorUserNameField;
            }
            set
            {
                this.AuthorUserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Time
        {
            get
            {
                return this.TimeField;
            }
            set
            {
                this.TimeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://DriveCam.com/Contracts", ConfigurationName="Vendor.Services.Drivecam.Submission.ISubmissionServiceV5")]
    public interface ISubmissionServiceV5
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/Ping", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/Login", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/LoginResponse")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.LoginResponse> LoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/LoginCompany", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/LoginCompanyResponse")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.LoginResponse> LoginCompanyAsync(string userName, string password, long companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/SubmitDriverDispatchLogs", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/SubmitDriverDispatchLogsRespon" +
            "se")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.SubmitDriverDispatchLogsResponse> SubmitDriverDispatchLogsAsync(string sessionId, string dispatchEntries);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetSubmissionStatus", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetSubmissionStatusResponse")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetSubmissionStatusResponse> GetSubmissionStatusAsync(string sessionId, long submissionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetSubmissionResults", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetSubmissionResultsResponse")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetSubmissionResultsResponse> GetSubmissionResultsAsync(string sessionId, long submissionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetVehicles", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetVehiclesResponse")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetVehiclesResponse> GetVehiclesAsync(Vendor.Services.Drivecam.Submission.GetVehiclesRequest getVehiclesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetVehicleTypes", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetVehicleTypesResponse")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetVehicleTypesResponse> GetVehicleTypesAsync(Vendor.Services.Drivecam.Submission.ExistingSessionRequest getVehicleTypesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetVehicleStatuses", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetVehicleStatusesResponse")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetVehicleStatusesResponse> GetVehicleStatusesAsync(Vendor.Services.Drivecam.Submission.ExistingSessionRequest getVehicleStatusesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetEventTypes", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetEventTypesResponse")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetEventTypesResponse> GetEventTypesAsync(Vendor.Services.Drivecam.Submission.ExistingSessionRequest getEventTypesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetEventStatuses", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetEventStatusesResponse")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetEventStatusesResponse> GetEventStatusesAsync(Vendor.Services.Drivecam.Submission.ExistingSessionRequest getEventStatusesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetBehaviors", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetBehaviorsResponse")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetBehaviorsResponse> GetBehaviorsAsync(Vendor.Services.Drivecam.Submission.ExistingSessionRequest getBehaviorsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetUsers", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetUsersResponse")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetUsersResponse> GetUsersAsync(Vendor.Services.Drivecam.Submission.GetUsersRequest getUsersRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetGroupsById", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetGroupsByIdResponse")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetGroupsResponse> GetGroupsByIdAsync(Vendor.Services.Drivecam.Submission.GetGroupsByIdRequest getGroupsByIdRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetGroupsByPath", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetGroupsByPathResponse")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetGroupsResponse> GetGroupsByPathAsync(Vendor.Services.Drivecam.Submission.GetGroupsByFullPathRequest getGroupsByFullPathRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetEventsByLastUpdateDate", ReplyAction="http://DriveCam.com/Contracts/ISubmissionServiceV5/GetEventsByLastUpdateDateRespo" +
            "nse")]
        System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetEventsResponse> GetEventsByLastUpdateDateAsync(Vendor.Services.Drivecam.Submission.GetEventsByLastUpdateDateRequest getEventsByLastUpdateDateRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISubmissionServiceV5Channel : Vendor.Services.Drivecam.Submission.ISubmissionServiceV5, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SubmissionServiceV5Client : System.ServiceModel.ClientBase<Vendor.Services.Drivecam.Submission.ISubmissionServiceV5>, Vendor.Services.Drivecam.Submission.ISubmissionServiceV5
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SubmissionServiceV5Client() : 
                base(SubmissionServiceV5Client.GetDefaultBinding(), SubmissionServiceV5Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISubmissionServiceV5.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubmissionServiceV5Client(EndpointConfiguration endpointConfiguration) : 
                base(SubmissionServiceV5Client.GetBindingForEndpoint(endpointConfiguration), SubmissionServiceV5Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubmissionServiceV5Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SubmissionServiceV5Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubmissionServiceV5Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SubmissionServiceV5Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubmissionServiceV5Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> PingAsync()
        {
            return base.Channel.PingAsync();
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.LoginResponse> LoginAsync(string userName, string password)
        {
            return base.Channel.LoginAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.LoginResponse> LoginCompanyAsync(string userName, string password, long companyId)
        {
            return base.Channel.LoginCompanyAsync(userName, password, companyId);
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.SubmitDriverDispatchLogsResponse> SubmitDriverDispatchLogsAsync(string sessionId, string dispatchEntries)
        {
            return base.Channel.SubmitDriverDispatchLogsAsync(sessionId, dispatchEntries);
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetSubmissionStatusResponse> GetSubmissionStatusAsync(string sessionId, long submissionId)
        {
            return base.Channel.GetSubmissionStatusAsync(sessionId, submissionId);
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetSubmissionResultsResponse> GetSubmissionResultsAsync(string sessionId, long submissionId)
        {
            return base.Channel.GetSubmissionResultsAsync(sessionId, submissionId);
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetVehiclesResponse> GetVehiclesAsync(Vendor.Services.Drivecam.Submission.GetVehiclesRequest getVehiclesRequest)
        {
            return base.Channel.GetVehiclesAsync(getVehiclesRequest);
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetVehicleTypesResponse> GetVehicleTypesAsync(Vendor.Services.Drivecam.Submission.ExistingSessionRequest getVehicleTypesRequest)
        {
            return base.Channel.GetVehicleTypesAsync(getVehicleTypesRequest);
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetVehicleStatusesResponse> GetVehicleStatusesAsync(Vendor.Services.Drivecam.Submission.ExistingSessionRequest getVehicleStatusesRequest)
        {
            return base.Channel.GetVehicleStatusesAsync(getVehicleStatusesRequest);
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetEventTypesResponse> GetEventTypesAsync(Vendor.Services.Drivecam.Submission.ExistingSessionRequest getEventTypesRequest)
        {
            return base.Channel.GetEventTypesAsync(getEventTypesRequest);
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetEventStatusesResponse> GetEventStatusesAsync(Vendor.Services.Drivecam.Submission.ExistingSessionRequest getEventStatusesRequest)
        {
            return base.Channel.GetEventStatusesAsync(getEventStatusesRequest);
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetBehaviorsResponse> GetBehaviorsAsync(Vendor.Services.Drivecam.Submission.ExistingSessionRequest getBehaviorsRequest)
        {
            return base.Channel.GetBehaviorsAsync(getBehaviorsRequest);
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetUsersResponse> GetUsersAsync(Vendor.Services.Drivecam.Submission.GetUsersRequest getUsersRequest)
        {
            return base.Channel.GetUsersAsync(getUsersRequest);
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetGroupsResponse> GetGroupsByIdAsync(Vendor.Services.Drivecam.Submission.GetGroupsByIdRequest getGroupsByIdRequest)
        {
            return base.Channel.GetGroupsByIdAsync(getGroupsByIdRequest);
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetGroupsResponse> GetGroupsByPathAsync(Vendor.Services.Drivecam.Submission.GetGroupsByFullPathRequest getGroupsByFullPathRequest)
        {
            return base.Channel.GetGroupsByPathAsync(getGroupsByFullPathRequest);
        }
        
        public System.Threading.Tasks.Task<Vendor.Services.Drivecam.Submission.GetEventsResponse> GetEventsByLastUpdateDateAsync(Vendor.Services.Drivecam.Submission.GetEventsByLastUpdateDateRequest getEventsByLastUpdateDateRequest)
        {
            return base.Channel.GetEventsByLastUpdateDateAsync(getEventsByLastUpdateDateRequest);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISubmissionServiceV5))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISubmissionServiceV5))
            {
                return new System.ServiceModel.EndpointAddress("https://services-sd02.drivecam.com/DCSubmission/SubmissionServiceV5.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SubmissionServiceV5Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISubmissionServiceV5);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SubmissionServiceV5Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISubmissionServiceV5);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISubmissionServiceV5,
        }
    }
}
